### PR TITLE
Fix issue causing lobs to skip some bytes when doing partial reads

### LINKED ISSUE #188: error calculating remaining bytes when reading from text lob stored in value_image
I ran into a problem trying to read an entire lob block after it had been loaded into the scanner value image from a previous get lob size call. I tracked down the issue to line 1925 in ion_reader_text.c where it updates the length of the remaining bytes.

The line currently reads: 
__text->_scanner._value_image.length -= remaining;_

but I think it should probably be setting the length to be equal to 'remaining' or just subtracting the bytes written.

It seems to work as I would expect with these changes in my local copy.

### PR DESCRIPTION
**Pull request by dlurton**
Fixes #188 

Also adds regression tests as well.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: test/test_ion_text.cpp [hunk 1]
```diff
@@ -576,6 +578,103 @@ TEST(IonTextDecimal, FailsEarlyOnInvalidDecimal) {
...
+    ASSERT_EQ(EXPECTED_SIZE, total_bytes_read);
+    char* lob_text = (char*)bytes;
+    ASSERT_EQ(strcmp("This is a CLOB of text.", lob_text), 0);
+
+    free(bytes);
+    ION_ASSERT_OK(ion_reader_close(reader));
+}
+ 
+// regression test for https://github.com/amzn/ion-c/issues/188
+TEST(IonTextblob, CanFullyReadBlobUsingPartialReadsAfterReadingSize) {
```
Comment (tgregg) [inline test/test_ion_text.cpp:655]: IonTextblob -> IonTextBlob

**Comment by dlurton** [comment]
I've refactored a bit to DRY some and also added equivalent tests for Ion binary.  The same bug does not exist for the binary reader.

**Comment by derivativerobmc** [comment]
thanks for fixing that so quickly
