### PR TITLE
Fixes a bug that caused an infinite loop when writing to a fixed-size buffer that is too small

### LINKED ISSUE #185: Small Buffer Causes Binary Writer Infinite Loop
The following test case causes an infinite loop--specifically for an over-small buffer that cannot possibly fit what is written.

```c
TEST(IonBinaryWriterBuffer, SmallBuffer) {
    iENTER;
    hWRITER writer = NULL;
    uint8_t buf[2];
    ION_WRITER_OPTIONS options = { 0 };
    options.output_as_binary = TRUE;
    ION_ASSERT_OK(ion_writer_open_buffer(&writer, buf, sizeof(buf), &options));
    ION_ASSERT_OK(ion_writer_write_int32(writer, 1));

    SIZE len;
    ION_ASSERT_FAIL(ion_writer_finish(writer, &len));
    ION_ASSERT_FAIL(ion_writer_close(writer));
}
```

### PR DESCRIPTION
**Pull request by tgregg**
*Issue #, if available:*

Fixes #185 

*Description of changes:*

* Fixes a bug that caused an infinite loop when writing to a fixed-size buffer that is too small.
* Adds a test to demonstrate how to use a user handler to grow the buffer when necessary.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: test/test_ion_stream.cpp [hunk 1]
```diff
@@ -103,3 +104,128 @@ TEST(IonStream, ContinuesOverPageBoundary) {
     ION_ASSERT_OK(ion_timestamp_equals(&expected, &ts, &is_equal, &g_IonEventDecimalContext));
     ASSERT_TRUE(is_equal);
 }
+
+TEST(IonStream, BufferTooSmall) {
+    iENTER;
+    hWRITER writer = NULL;
+    uint8_t buf[2]; // This buffer is to small to hold the output.
```
Comment (zslayton) [inline test/test_ion_stream.cpp:111]:
```suggestion
    uint8_t buf[2]; // This buffer is too small to hold the output.
```

**Review by zslayton — DISMISSED** [review]

**Review by zslayton — APPROVED** [review]
